### PR TITLE
Rename PRODUCT_NAME and PRODUCT_DEVICE to kccat6 for consistency.

### PR DESCRIPTION
**Pull request by ruchern**
Signed-off-by: Ru Chern Chong <iruchern@gmail.com>

### CODE REVIEW

**Comment by github-cygwin** [comment]
Hmm, not sure about that.  I modelled the values after our sister device klte.

See https://github.com/LineageOS/android_device_samsung_klte/blob/cm-14.1/full_klte.mk

Corinna

**Comment by github-cygwin** [comment]
OTOH, the klte has many variants while kccat6 has only one...

**Comment by ruchern** [comment]
I see. So in this case, just ignore this changes?

**Comment by github-cygwin** [comment]
Yes, I think we should follow klte's lead here

**Pull request closed without merging**
